- name: installing redis rpm redis file
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enable Redis 6.2 from package streams
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: installing redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: updating listed address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: starting and enabling redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes

