- name: copying repo file for mongodb
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: updating listed address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting and enabling mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

