- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove existing nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating nginx content directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory