- name: CentOS-8 Comes with MySQL 8 Version by default, However our application needs MySQL 5.7. So lets disable MySQL 8 version.
  ansible.builtin.shell: dnf module disable mysql

- name: copy mysql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: installing mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start and enable mysql
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: change mysql default root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_root_password}}
  register: out
  ignore_errors: yes

- name: password status
  ansible.builtin.debug:
    msg: password is already changed!!
  when: out.rc == 1
