- name: adding user
  ansible.builtin.user:
    name: roboshop

- name: removing old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: downloading and extract the app content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes
- name: downloading and extract the app content
  ansible.builtin.unarchive:
    src: https://172.31.1.57:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes
