- name: installing maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: include apppreq tasks
  ansible.builtin.include_tasks:
    file: app_prereq.yml

- name: installing maven depedencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: include systemd setup tasks
  ansible.builtin.include_tasks:
    file: systemd_setup.yml

- name: include mysql schema
  ansible.builtin.include_tasks:
    file: mysql_schema.yml
  when: schema_load

- name: restart shipping
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted