- name: installing mysql and pyMySql
  ansible.builtin.yum:
    name:
      - mysql
      - python3-PyMySQL
    state: installed

- name: load mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.nvrnagella.online
    login_user: root
    login_password: "{{mysql_root_password}}"