- name: setup nodejs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: installing nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: including app prereq tasks
  ansible.builtin.include_tasks:
    file: app_prereq.yml

- name: installing nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: including systemd setup tasks
  ansible.builtin.include_tasks:
    file: systemd_setup.yml

- name: including schema load tasks
  ansible.builtin.include_tasks:
    file: schema_load.yml
  when: schema_load


