- name: setup nodejs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: installing nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: including app prereq tasks
  ansible.builtin.include_tasks:
    file: app_prereq.yml

- name: installing nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: including systemd setup tasks
  ansible.builtin.include_tasks:
    file: systemd_setup.yml

#- name: including schema load tasks
#  ansible.builtin.include_tasks:
#    file: schema_load.yml
#  when: schema_load

- name: coping repo file for mongodb
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: loading mongodb schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.nvrnagella.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes
