- name: coping repo file for mongodb
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: loading mongodb schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.nvrnagella.online
    file: /app/schema/{{component}}.js
    idempotent: yes